# Name of storage directory
PYXIS_STORAGE_DIR = ".pyxis_data"

# Constant cmds names
STORE = "STORE"
FETCH = "FETCH"
DOWNLOAD = "DOWNLOAD"
CONNECT = "CONNECT"
REMOTE = "REMOTE"
CLIENT = "CLIENT"
DISCONNECT = "DISCONNECT"
DATA = "DATA"
DATA_STORED = "DATA_STORED"

